# Generated by Django 5.0.3 on 2024-09-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('technician', 'Technician')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerLab',
            fields=[
                ('computerlab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab', models.CharField(max_length=100)),
                ('total_units', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=100)),
                ('pc_number', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField()),
                ('computerlab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comlab_system.computerlab')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comlab_system.status')),
            ],
        ),
    ]
