# Generated by Django 5.0.3 on 2024-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('personnel', 'personnel')], max_length=20),
        ),
    ]
