# Generated by Django 5.0.3 on 2024-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0002_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='count',
        ),
    ]
