# Generated by Django 5.0.3 on 2024-09-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0003_remove_unit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('monitor', models.BooleanField(default=False)),
                ('keyboard', models.BooleanField(default=False)),
                ('mouse', models.BooleanField(default=False)),
                ('ram', models.BooleanField(default=False)),
                ('motherboard', models.BooleanField(default=False)),
                ('cpu', models.BooleanField(default=False)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comlab_system.status')),
            ],
        ),
    ]
