# Generated by Django 5.0.3 on 2024-09-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0004_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comlab_system.components'),
        ),
    ]
