# Generated by Django 5.0.3 on 2024-09-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0006_alter_components_cpu_alter_components_keyboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='status',
        ),
    ]
