# Generated by Django 5.0.3 on 2024-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0007_remove_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stat_cpu',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='stat_keyboard',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='stat_monitor',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='stat_motherboard',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='stat_mouse',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='stat_ram',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], default='Functional', max_length=15),
        ),
    ]
