# Generated by Django 5.0.3 on 2024-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0008_status_stat_cpu_status_stat_keyboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='stat_cpu',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_keyboard',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_monitor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_motherboard',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_mouse',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_ram',
            field=models.CharField(max_length=15),
        ),
    ]
