# Generated by Django 5.0.3 on 2024-10-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0009_alter_status_stat_cpu_alter_status_stat_keyboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
    ]
