# Generated by Django 5.1.3 on 2024-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comlab_system', '0010_remove_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlab',
            name='lab_images',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/'),
        ),
    ]
